'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.544
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property Havok_Weapons_UDPInterval() As Integer
            Get
                Return CType(Me("Havok_Weapons_UDPInterval"),Integer)
            End Get
            Set
                Me("Havok_Weapons_UDPInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Havok_Interface_VisualStyling() As Integer
            Get
                Return CType(Me("Havok_Interface_VisualStyling"),Integer)
            End Get
            Set
                Me("Havok_Interface_VisualStyling") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Havok_Interface_SystemStats() As Integer
            Get
                Return CType(Me("Havok_Interface_SystemStats"),Integer)
            End Get
            Set
                Me("Havok_Interface_SystemStats") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Havok_Interface_ChestaGUI() As Integer
            Get
                Return CType(Me("Havok_Interface_ChestaGUI"),Integer)
            End Get
            Set
                Me("Havok_Interface_ChestaGUI") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Havok_Environment_Lockdown() As Integer
            Get
                Return CType(Me("Havok_Environment_Lockdown"),Integer)
            End Get
            Set
                Me("Havok_Environment_Lockdown") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("about:blank")>  _
        Public Property Havok_Browser_HomepageURL() As String
            Get
                Return CType(Me("Havok_Browser_HomepageURL"),String)
            End Get
            Set
                Me("Havok_Browser_HomepageURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UDP-Flooder")>  _
        Public Property Havok_Environment_LastTyped_LastSelectedWeapon() As String
            Get
                Return CType(Me("Havok_Environment_LastTyped_LastSelectedWeapon"),String)
            End Get
            Set
                Me("Havok_Environment_LastTyped_LastSelectedWeapon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("true")>  _
        Public Property Havok_Environment_FirstRun() As String
            Get
                Return CType(Me("Havok_Environment_FirstRun"),String)
            End Get
            Set
                Me("Havok_Environment_FirstRun") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Havok_Environment_LastTyped_LastTypedIPAddress() As String
            Get
                Return CType(Me("Havok_Environment_LastTyped_LastTypedIPAddress"),String)
            End Get
            Set
                Me("Havok_Environment_LastTyped_LastTypedIPAddress") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Havok_Environment_LastTyped_LastTypedPort() As String
            Get
                Return CType(Me("Havok_Environment_LastTyped_LastTypedPort"),String)
            End Get
            Set
                Me("Havok_Environment_LastTyped_LastTypedPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Havok_Environment_LastTyped_LastTypedMiscBox() As String
            Get
                Return CType(Me("Havok_Environment_LastTyped_LastTypedMiscBox"),String)
            End Get
            Set
                Me("Havok_Environment_LastTyped_LastTypedMiscBox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("true")>  _
        Public Property Havok_Environment_RememberLastTyped() As String
            Get
                Return CType(Me("Havok_Environment_RememberLastTyped"),String)
            End Get
            Set
                Me("Havok_Environment_RememberLastTyped") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("true")>  _
        Public Property Havok_Interface_CurrentTimeClockEnabled() As String
            Get
                Return CType(Me("Havok_Interface_CurrentTimeClockEnabled"),String)
            End Get
            Set
                Me("Havok_Interface_CurrentTimeClockEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("false")>  _
        Public Property Havok_Interface_Extensions_NetMon_InStatusBar() As String
            Get
                Return CType(Me("Havok_Interface_Extensions_NetMon_InStatusBar"),String)
            End Get
            Set
                Me("Havok_Interface_Extensions_NetMon_InStatusBar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("true")>  _
        Public Property Havok_Interface_StatusBarVisible() As String
            Get
                Return CType(Me("Havok_Interface_StatusBarVisible"),String)
            End Get
            Set
                Me("Havok_Interface_StatusBarVisible") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("true")>  _
        Public Property Havok_Interface_OptionsButtonVisible() As String
            Get
                Return CType(Me("Havok_Interface_OptionsButtonVisible"),String)
            End Get
            Set
                Me("Havok_Interface_OptionsButtonVisible") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("true")>  _
        Public Property Havok_Interface_Browser_StatusTextVisible() As String
            Get
                Return CType(Me("Havok_Interface_Browser_StatusTextVisible"),String)
            End Get
            Set
                Me("Havok_Interface_Browser_StatusTextVisible") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("true")>  _
        Public Property Havok_Interface_Browser_NotifyOnRedirect() As String
            Get
                Return CType(Me("Havok_Interface_Browser_NotifyOnRedirect"),String)
            End Get
            Set
                Me("Havok_Interface_Browser_NotifyOnRedirect") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("true")>  _
        Public Property Havok_Interface_Browser_NotifyOnJavascriptError() As String
            Get
                Return CType(Me("Havok_Interface_Browser_NotifyOnJavascriptError"),String)
            End Get
            Set
                Me("Havok_Interface_Browser_NotifyOnJavascriptError") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("true")>  _
        Public Property Havok_Browser_NotifyOnSecurityStateChanged() As String
            Get
                Return CType(Me("Havok_Browser_NotifyOnSecurityStateChanged"),String)
            End Get
            Set
                Me("Havok_Browser_NotifyOnSecurityStateChanged") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("false")>  _
        Public Property Havok_Environment_HideOnStartup() As String
            Get
                Return CType(Me("Havok_Environment_HideOnStartup"),String)
            End Get
            Set
                Me("Havok_Environment_HideOnStartup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property Havok_Extensions_NetMon_TimerInterval() As String
            Get
                Return CType(Me("Havok_Extensions_NetMon_TimerInterval"),String)
            End Get
            Set
                Me("Havok_Extensions_NetMon_TimerInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("true")>  _
        Public Property Havok_Environment_DevMessage() As String
            Get
                Return CType(Me("Havok_Environment_DevMessage"),String)
            End Get
            Set
                Me("Havok_Environment_DevMessage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("true")>  _
        Public Property Havok_Interface_WindowHeaderBarEnabled() As String
            Get
                Return CType(Me("Havok_Interface_WindowHeaderBarEnabled"),String)
            End Get
            Set
                Me("Havok_Interface_WindowHeaderBarEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("true")>  _
        Public Property Havok_Interface_MenuStripEnabled() As String
            Get
                Return CType(Me("Havok_Interface_MenuStripEnabled"),String)
            End Get
            Set
                Me("Havok_Interface_MenuStripEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("false")>  _
        Public Property Havok_Interface_UseDoubleBuffers() As String
            Get
                Return CType(Me("Havok_Interface_UseDoubleBuffers"),String)
            End Get
            Set
                Me("Havok_Interface_UseDoubleBuffers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("false")>  _
        Public Property Havok_Weapons_ViewSource_AutoRefresh() As String
            Get
                Return CType(Me("Havok_Weapons_ViewSource_AutoRefresh"),String)
            End Get
            Set
                Me("Havok_Weapons_ViewSource_AutoRefresh") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property Havok_Weapons_ViewSource_AutoRefresh_RefreshInterval() As String
            Get
                Return CType(Me("Havok_Weapons_ViewSource_AutoRefresh_RefreshInterval"),String)
            End Get
            Set
                Me("Havok_Weapons_ViewSource_AutoRefresh_RefreshInterval") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Havok.My.MySettings
            Get
                Return Global.Havok.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
